### ISSUE TITLE
Jump in flow of diagram

### ISSUE THREAD

**Issue by thomastthai** [atreya2011/go-kratos-test#10]
Your diagram was helpful to see the flow between the browser, Kratos, and Hydra.

There is a jump in the flow as highlighted in the attachment. Was that intentional?

![Screenshot_20240312_155138_Brave](https://github.com/atreya2011/go-kratos-test/assets/16532581/90ea52c9-d4d5-4021-a035-91e44de5436b)

**Comment by atreya2011** [comment]
@thomastthai Yes that is correct
