### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by schreddies** [atreya2011/go-kratos-test#2]
Hi, 
Thank you so much for this code, it will make my life easier. May I ask you for some instruction for deployment instruction. `docker-compose up` seems not working

**Comment by atreya2011** [comment]
Hello, I will try updating the README with the instructions within the next few days. In the meantime, the following are instructions for deployment.
Let me know if it works for you.

Also, I have posted solutions to some common unresolved issues over here :)
https://github.com/atreya2011/go-kratos-test/issues/1#issuecomment-982336976 

There are 4 branches at the moment:
- **main**: contains a kratos only implementation
- **hydra**: kratos + hydra without consent page implementation
- **hydra-consent**: kratos + hydra with a yet to implement consent page
- **microsoft-oidc**: kratos only implementation with Microsoft social login (as an answer to this StackOverflow question: https://stackoverflow.com/questions/70034185/ory-kratos-login-page-for-login-with-microsoft)

To try out the `kratos only` implementation, you need to have Docker installed and then do the following:

1. Clone the repository locally.
2. Run `docker-compose up --build` in one terminal session
3. Then in your browser, open, http://localhost:4455/login

To try out the reference `kratos + hydra` implementation, you need to have
- Docker installed
- Register a dummy account first using the `kratos only` implementation in the main branch! Sorry about this 🙇🏼‍♂️ 

And then do the following:

1. Clone the repository locally.
2. `git checkout hydra-consent`
3. Run `docker-compose up --build` in one terminal session (in case hydra fails to startup, run `docker-compose down` and `docker-compose up --build` again)

4. In yet another terminal session, create an OAuth2 Client

```shell script
docker-compose exec hydra \
    hydra clients create \
    --endpoint http://127.0.0.1:4445 \
    --id auth-code-client \
    --secret secret \
    --grant-types authorization_code,refresh_token \
    --response-types code,id_token \
    --scope openid,offline \
    --callbacks http://127.0.0.1:5555/callback
```

5. And perform an OAuth2 Authorize Code Flow

```shell script
docker-compose exec hydra \
    hydra token user \
    --client-id auth-code-client \
    --client-secret secret \
    --endpoint http://127.0.0.1:4444/ \
    --port 5555 \
    --scope openid,offline
```

I still have to address the following issues:

- Consent UI Implementation
- User breaks login flow if they try to register a new account and gets back to the login screen (keep a hydra login flow state like the reference Node.js implementation, and this is the reason why an account has to be registered first using the `kratos only` implementation before trying out the hydra integration branch)

**Comment by schreddies** [comment]
@atreya2011 thank you a lot! 
I am interested in making the hydra as the Authorization Server, because it seems to address my idea of making `oidc` with API, am I right? So `hydra` branch?

**Comment by atreya2011** [comment]
Ah I see, you can try checking out the `hydra-consent` branch instead of the `hydra` branch. And let me know if you are facing any issues.

**Comment by atreya2011** [comment]
@schreddies Were you able to set up and try out the hydra-consent branch? Let me know if you are having an issues 🙏🏼

**Comment by thomastthai** [comment]
@atreya2011, your repo is an excellent way to help people get started with the Ory suite, in particular, `hydra` and `kratos`.

From reading all your replies to issues, documenting how people can use the repo and consolidating your answers to issues in  a `README.md` may add more value and save you and others lots of time.
