### ISSUE TITLE
Issue following the 2nd step in the README.md

### ISSUE THREAD

**Issue by jonnyijapan** [atreya2011/go-kratos-test#5]
first step: 
```
docker-compose up -d --build
```

second step:
```
curl -X POST 'http://localhost:4445/clients' \
-H 'Content-Type: application/json' \
--data-raw '{
  "client_id": "auth-code-client",
  "client_name": "Test OAuth2 Client",
  "client_secret": "secret",
  "grant_types": ["authorization_code", "refresh_token"],
  "redirect_uris": ["http://localhost:4455/dashboard"],
  "response_types": ["code", "id_token"],
  "scope": "openid offline",
  "token_endpoint_auth_method": "client_secret_post",
  "metadata": {"registration": true, "consent": true}
}'
```

<< this step fails with 

> curl: (7) Failed to connect to localhost port 4445 after 6 ms: Connection refused

I think the port in the 2nd step is incorrect. Should it not be 4455?
Changing the command to use 4455, it renders no response. Maybe that is the correct, expected way.

**Comment by jonnyijapan** [comment]
Doh realized I was using the wrong (main) branch after cloning. Changing to branch hydra-consent, and it seems fine so far. My bad.

**Comment by atreya2011** [comment]
@jonnyijapan 
Glad you got this resolved :)
Let me know if you are having any other issues.
I will update the README to include instructions for switching to the correct branch.

**Comment by jonnyijapan** [comment]
I rebuilt the container and launch it and created a client, then tried to signup but never received that email so couldn't proceed from there.

**Comment by atreya2011** [comment]
@jonnyijapan 
You can check the mail using mailslurper running on localhost:4436
