### ISSUE TITLE
Path /oauth2/auth/requests/login returns 404

### ISSUE THREAD

**Issue by paulbalomiri** [atreya2011/go-kratos-test#7]
Hi, i'm stuck here for quite some time with a problem you might have encountered:
The call to the hydra public endpoint at path `/oauth2/auth/requests/login` fails with a 404 Error returned in ~html format~.

**EDIT:** in code this is returned, i guess the response format is determined by request headers:
```json
{
  "error": {
     "code": 404,
     "message": "Not Found",
     "reason": "The requested route does not exist. Make sure you are using the right path, domain, and port."
  }
}
```

This is happening at this code branch (in the `hydra-consent` branch):

https://github.com/atreya2011/go-kratos-test/blob/d814b51cfb6c4f3d3cafd76b3f8f219c2f4506c3/main.go#L222-L228

Perhaps you encountered this before?

**Comment by atreya2011** [comment]
@paulbalomiri 
My apologies for the late reply. Can you try the instructions in the readme (https://github.com/atreya2011/go-kratos-test/tree/hydra-consent#readme) and let me know if you are still facing this error.
Before you try the instructions, please do the following.

```shell
docker-compose down 
docker system prune -f --volumes
```

**Comment by paulbalomiri** [comment]
I had to add some basic auth & exclusion mechanism to protect admin access to hydra which I use publicly.
I'm pretty far away now from the standard setup, but i'll give it a try next week, when i'll move the setup to a central location.


> late reply

It must've been the quickest late reply 😃  Thanks for this project. ❤️

**Comment by paulbalomiri** [comment]
Finally, The 404, was just a misconfiguration of hydra's  reverse proxy. `go-kratos-test`  had no problem. In my branch I've added 

- some logging for each outgoing/incoming request
- some configuration from Env, but given that i do not usually work in go, it's of low quality.

For the logging part I could create a PR, though. That would be via  [`import ( _ "github.com/motemen/go-loghttp/global")`](https://github.com/motemen/go-loghttp/)

**Comment by atreya2011** [comment]
@paulbalomiri 

Glad you got it working! 🙂 

> For the logging part I could create a PR, though. That would be via [import ( _ "github.com/motemen/go-loghttp/global")](https://github.com/motemen/go-loghttp/)

Is it ok if I can take a look at how you are using this loggin library. I am using `logrus` at the moment and would like to know if the above logging library is compatible with `logrus`.

**Comment by paulbalomiri** [comment]
Yes, sure, np. I intend to replace this lib in my stack with a react - UI implementation.
I think this logging lib (go-loghttp) relies on the standard [go log lib](https://github.com/motemen/go-loghttp/blob/974ac5ceac271576caabe1c0bddf2b7eed471f67/loghttp.go#L6-L13)

Tell me if I can assist. I'm returning to this topic in a couple of hrs.

@atreya2011 My fork can be found [here](https://github.com/kwanta-cante/go-kratos-test)

**Comment by atreya2011** [comment]
@paulbalomiri Sorry for not being able to get back regarding this issue sooner. I took a look at your fork, and if you can make a PR whenever you are free, maybe it will be easier for me to review the changes that you are proposing 🙏🏼 No need to hurry with the PR 🙂
