### ISSUE TITLE
User identity id is not attached in access token

### ISSUE THREAD

**Issue by jcbriones** [atreya2011/go-kratos-test#8]
User identity id is not attached in access token

**Comment by atreya2011** [comment]
@jcbriones sorry for the late response, can you be more specific about this issue?

**Comment by jcbriones** [comment]
The subject is not the user's identity id. But I updated to the latest hydra and kratos and it seems to be working from those now.

**Comment by atreya2011** [comment]
@jcbriones Glad you got it resolved. Can you let me know which versions of Kratos and Hydra?
